import Navbar from "components/Navbar";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Sidebar from "components/Sidebar";
import Featured from "components/Featured";
import Rightbar from "components/Rightbar";
import Footer from "components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Navbar */}
      <Navbar />
      {/*Sidebar */}

      <div className="grid grid-cols-4">
        <Sidebar />
        <div className="col-span-2">
          <Featured />
        </div>
        <Rightbar />
      </div>

      <Footer />
    </div>
  );
}
